---

- name: Updatings
  apt:
    update_cache: yes
    upgrade: yes

- name: Installings
  apt:
    name: "{{ packages }}"
    state: latest

- name: Docker
  apt:
    name: "{{ install_docker }}"
    state: latest
