---
  - name: Import git repo
    git:
      repo: https://github.com/GNUKalashnikov/ansible-nextcloud.git
      dest: /root/host
      clone: yes
      update: yes
  
  - name: Adding a .env file
    ansible.builtin.file:
    path: /root/host/.env
    state: touch
    mode: u=rw,g=r,o=r
  
  - name: Alter file with variables
    ansible.builtin.blockinfile:
      path: /root/host/.env
      block: | 
        $MYSQL_ROOT_PASSWORD={{ MYSQL_ROOT_PASSWORD }}
        $MYSQL_PASSWORD={{ MYSQL_PASSWORD }}
        $NEXTCLOUD_ADMIN_PASSWORD={{ NEXTCLOUD_ADMIN_PASSWORD }}
        $NEXTCLOUD_ADMIN_USER={{ NEXTCLOUD_ADMIN_USER }}

    