---
  - name: Import git repo
    git:
      repo: https://github.com/GNUKalashnikov/ansible-nextcloud.git
      dest: "{{ STORAGE_LOCATION }}"
      clone: yes
      force: yes
      update: yes
  
  - name: Adding a env file
    ansible.builtin.file:
      path: "{{ STORAGE_LOCATION }}/.env"
      state: touch
      mode: u=rw,g=r,o=r
  
  - name: Alter file with variables
    ansible.builtin.blockinfile:
      path: "{{ STORAGE_LOCATION }}/.env"
      block: | 
        STORAGE_LOCATION={{ STORAGE_LOCATION }}
        MYSQL_ROOT_PASSWORD={{ MYSQL_ROOT_PASSWORD }}
        MYSQL_PASSWORD={{ MYSQL_PASSWORD }}
        MYSQL_DATABASE={{ MYSQL_DATABASE }}
        MYSQL_USER={{ MYSQL_USER }}
        NEXTCLOUD_ADMIN_PASSWORD={{ NEXTCLOUD_ADMIN_PASSWORD }}
        NEXTCLOUD_ADMIN_USER={{ NEXTCLOUD_ADMIN_USER }}
        NEXTCLOUD_TRUSTED_DOMAINS={{ NEXTCLOUD_TRUSTED_DOMAINS }}
        OVERWRITEPROTOCOL={{ OVERWRITEPROTOCOL }}
        CLIENT_MAX_BODY_SIZE={{ CLIENT_MAX_BODY_SIZE }}
        UPLOAD_MAX_FILESIZE={{ UPLOAD_MAX_FILESIZE }}
        PHP_MEMORY_LIMIT={{ PHP_MEMORY_LIMIT }}
  
  - name: Moving the Nginx config file
    ansible.builtin.copy:
      src: "{{ STORAGE_LOCATION }}/docker"
      dest: /etc/nginx/sites-enabled
      remote_src: yes
  
  - name: Shutdown the running service
    community.docker.docker_compose_v2:
      project_src: "{{ STORAGE_LOCATION }}"
      state: absent
  
  - name: Create and start services
    community.docker.docker_compose_v2:
        project_src: "{{ STORAGE_LOCATION }}"
        env_files: "{{ STORAGE_LOCATION }}/.env"
    register: output

  - ansible.builtin.debug:
        var: output