---
  - name: Import git repo
    git:
      repo: https://github.com/GNUKalashnikov/ansible-nextcloud.git
      dest: /root/host
      clone: yes
      update: yes
  
  - name: Adding a env file
    ansible.builtin.file:
      path: /root/host/.env
      state: touch
      mode: u=rw,g=r,o=r
  
  - name: Alter file with variables
    ansible.builtin.blockinfile:
      path: /root/host/.env
      block: | 
        MYSQL_ROOT_PASSWORD={{ MYSQL_ROOT_PASSWORD }}
        MYSQL_PASSWORD={{ MYSQL_PASSWORD }}
        MYSQL_DATABASE={{ MYSQL_DATABASE }}
        MYSQL_USER={{ MYSQL_USER }}
        NEXTCLOUD_ADMIN_PASSWORD={{ NEXTCLOUD_ADMIN_PASSWORD }}
        NEXTCLOUD_ADMIN_USER={{ NEXTCLOUD_ADMIN_USER }}
        NEXTCLOUD_TRUSTED_DOMAINS={{ NEXTCLOUD_TRUSTED_DOMAINS }}
        OVERWRITEPROTOCOL={{ OVERWRITEPROTOCOL }}
        CLIENT_MAX_BODY_SIZE={{ CLIENT_MAX_BODY_SIZE }}
        UPLOAD_MAX_FILESIZE={{ UPLOAD_MAX_FILESIZE }}
  
  - name: Moving the Nginx config file
    ansible.builtin.copy:
      src: /root/host/docker
      dest: /etc/nginx/sites-enabled
      remote_src: yes
  
  - name: Shutdown the running service
    community.docker.docker_compose:
      project_src: /root/host
      state: absent
  
  - name: Create and start services
    community.docker.docker_compose:
        project_src: /root/host
        env_file: /root/host/.env
    register: output

  - ansible.builtin.debug:
        var: output
      
      

  

    