---
username: ivan
packages:
  - vim
  - htop
  - neofetch
  - docker
  - curl
  - ca-certificates
  - gnupg
  - lsb-release

install_docker:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-buildx-plugin 
  - docker-compose-plugin

