---
username: ivan
packages:
  - vim
  - htop
  - neofetch
  - docker
  - curl
  - ca-certificates
  - gnupg
  - lsb-release

install_docker:
  - docker
  - docker-compose
  - docker-doc
  - docker-registry
  - docker.io